class TextConstant{
  static const String simulate = "Simule ";
  static const String now = "agora";
  static const String creditBenefits = "Crédito rápido, fácil e seguro! :)";
  static const String proceed = "Continuar";
  static const String whatsYour = "Qual seu ";
  static const String fullNameQuestion = "nome completo?";
  static const String fullName = "Nome Completo";
  static const String itsYour = "E seu ";
  static const String emailQuestion = "e-mail?";
  static const String emailExample = "seuemail@email.com";
  static const String emailInvalid = "Email inválido";
  static const String nameInvalid = "O nome deve conter caracteres de a-z ou A-Z";
  static const String howMuch = "De quanto ";
  static const String youNeedQuestion = "você precisa?";
  static const String insertValue = "Insara um valor entre ";
  static const String value500 = "R\$500 ";
  static const String a = "a ";
  static const String value300000 = "R\$300.000";
  static const String symbolCifrao = "R\$ ";
  static const String number25000 = "25.000";
  static const String amountInvalid = "Valor inválido";
  static const String amountNegativeInvalid = "Valor deve ser acima de R\$500";
  static const String amountPositiveInvalid = "Valor deve ser abaixo de R\$300.000";
  static const String amountChosen = "Valor escolhido";
  static const String addGuarantee = "Adicionar garantia";
  static const String protectedWarranty = "Garantia protegida";
  static const String textWarranty = "Bitcoin caiu? Fique tranquilo! Na garantia protegida, você não recebe chamada de margem e não é liquidado.";
  static const String choiceTheF = "Escolha a ";
  static const String choiceTheM = "Escolha o ";
  static const String quantityInstallments = "quantidade de parcelas";
  static const String percentageWarranty = "percentual de garantia";
  static const String continueWithoutWarranty = "Continuar sem garantia";
  static const String waitMoment = "Aguarde um momento";
  static const String simulatingOrder = "Estamos simulando seu pedido de crédito Rispar...";
  static const String newSimulation = "Nova simulação";
  static const String resultSimulation = "Resultado da simulação";

}